SHOW DATABASES;

USE ESTAGIO;

DESC ESTAGIO;

SHOW TABLES;

DROP DATABASE ESTAGIO;

SHOW TABLES;

CREATE DATABASE ESTAGIO;
USE ESTAGIO;

SHOW TABLES;

CREATE TABLE ENTRADAS (
	ID_ENTRADA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(45),
    DATA_HORA_ENTRADA DATETIME, 
    ID_TIPO_ENTRADA INT
);

CREATE TABLE TIPO_ENTRADAS(
	ID_TIPO_ENTRADA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45)
);

ALTER TABLE ENTRADAS ADD FOREIGN KEY (ID_TIPO_ENTRADA) REFERENCES TIPO_ENTRADAS(ID_TIPO_ENTRADA);

DESCRIBE ENTRADAS;

CREATE TABLE SAIDAS (
	ID_SAIDA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(45),
    DATA_HORA_SAIDA DATETIME, 
    ID_TIPO_SAIDA INT
);

CREATE TABLE SAIDA(
	ID_TIPO_SAIDA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45)
);

ALTER TABLE SAIDAS ADD FOREIGN KEY (ID_TIPO_SAIDA) REFERENCES SAIDA(ID_TIPO_SAIDA);

DESC SAIDAS;
USE ESTAGIO;
ALTER TABLE ENTRADAS ADD COLUMN VALOR_ENTRADA DOUBLE;
ALTER TABLE SAIDAS ADD COLUMN VALOR_SAIDA DOUBLE;

DESC ENTRADAS;